export default [
    "Oh yeah",
    "I guarantee I got ya\n",

    "I’ve been craving for your love",
    "Can’t see nobody but us",
    "So I, so I, so I",
    "See you from across the room",
    "Make my way over to you",
    "I’m trippin’ over butterflies\n",

    "Oh yeah, baby, I don’t really mean to rush",
    "But I’ma really need your touch",
    "If I’ma make it through the night",
    "I got the moonlight",
    "Tequila sunrise",
    "Ha, come take a shot on me, I got ya\n",

    "I don’t know how to say this",
    "I hope this song’s on your playlist",
    "This feeling’s so hard to explain",
    "I don’t even know how to talk right now",
    "It’s “I need you” o’clock right now",
    "I want you to hear me say\n",

    "Moonlight sunrise, baby, come be my starlight",
    "Moonlight sunrise, oh baby, just to make you\n  stay",
    "Moonlight sunrise, baby, let’s do it all night",
    "Moonlight sunrise, I guarantee I got ya\n",

    "Loving undefeated, on your knees pleading",
    "Baby, you can hit up my line when you need it",
    "Said that you tried? Baby, you succeeded",
    "Got a craving, baby, can you feed it?",
    "Took a trip under moonlight",
    "Follow me to the sunrise",
    "Everyday, every night",
    "Ay, come with me, don’t think twice\n",

    "Oh yeah, baby, I don’t really mean to rush",
    "But I’ma really need your touch",
    "If I’ma make it through the night",
    "I got the moonlight",
    "Tequila sunrise",
    "Ha, come take a shot on me, I got ya\n",

    "I don’t know how to say this",
    "I hope this song’s on your playlist",
    "This feeling’s so hard to explain",
    "I don’t even know how to talk right now",
    "It’s “I need you” o’clock right now",
    "I want you to hear me say\n",

    "Moonlight sunrise, baby, come be my starlight",
    "Moonlight sunrise, oh baby, just to make you\n  stay",
    "Moonlight sunrise, baby, let’s do it all night",
    "Moonlight sunrise, I guarantee I got ya\n",

    "Cards out on the table, what you say?",
    "I need you, you need me, you’re mine",
    "I’m your moonlight, you’re my sunrise, babe",
    "I guarantee I got ya\n",

    "Moonlight sunrise, baby, come be my starlight",
    "Moonlight sunrise, oh baby, just to make you\n  stay",
    "Moonlight sunrise, baby, let’s do it all night",
    "Moonlight sunrise, I guarantee I got ya\n",

    "Moonlight sunrise, baby, come be my starlight",
    "Moonlight sunrise, I guarantee I got ya",
    "Moonlight sunrise, baby, let’s do it all night",
    "Moonlight sunrise, I guarantee I got ya\n",

    "Moonlight sunrise",
]
